### ISSUE TITLE
negative fluxes in reduced spectra?

### ISSUE THREAD

**Issue by svenbuder** [svenbuder/GALAH_DR4#50]
150901003001378

**Comment by sheliak** [comment]
This particular fibre is weird. Looks like the measured throughput is way off. Fibre next to it has similar signal and is perfectly fine. Maybe the flat field lamp and starlight illuminate the fibre differently. I don't think there is anything I can do to make this reduce correctly.

**Comment by svenbuder** [comment]
Decision: Flag all stars with negative SNR in any CCD (indicating negative flux and thus negative uncertainties).
